all:
  hosts:
    k8s-1:
      ansible_host: 192.168.56.11
      ip: 192.168.56.11
      access_ip: 192.168.56.11
    k8s-2:
      ansible_host: 192.168.56.12
      ip: 192.168.56.12
      access_ip: 192.168.56.12
    k8s-3:
      ansible_host: 192.168.56.13
      ip: 192.168.56.13
      access_ip: 192.168.56.13
    k8s-4:
      ansible_host: 192.168.56.14
      ip: 192.168.56.14
      access_ip: 192.168.56.14
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: "{{ inventory_dir }}/../.vagrant/machines/{{ inventory_hostname }}/libvirt/private_key"
  children:
    kube_control_plane:
      hosts:
        k8s-1:
        k8s-2:
        k8s-3:
        k8s-4:
    kube_node:
      hosts:
        k8s-1:
        k8s-2:
        k8s-3:
        k8s-4:
    etcd:
      hosts:
        k8s-1:
        k8s-2:
        k8s-3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
