---
- name: Common config
  import_playbook: common_setup_tasks.yml

- hosts: all
  become: true
  tasks:

  - name: Join node to cluster
    command:
      cmd: sh /vagrant/work/join-command.sh
      creates: /etc/kubernetes/kubelet.conf
    register: kubernetes_join
  - debug:
      msg: "{{ kubernetes_join.stdout_lines }}"

- name: Setup vagrant user
  import_playbook: vagrant_kube_config.yml
