---

- name: Add an apt signing key for Kubernetes
  shell: curl -fsSL {{ k8s_url_apt_key }} | gpg --dearmor -o {{ k8s_gpgpath }}
  args:
    creates: "{{ k8s_gpgpath }}"

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: "deb [signed-by={{ k8s_gpgpath }}] {{ k8s_repository }} /"
    state: present
    filename: kubernetes.list
    update_cache: yes

- name: Install Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni
    state: present
    update_cache: yes

- name: Hold Kubernetes packages at current version
  shell: apt-mark hold kubelet kubeadm kubectl

- name: Configure node ip for kubelet
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
    create: yes
  register: kubelet_updated

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
  when: kubelet_updated is changed