---
- block:
  - stat:
      path: /etc/kubernetes/admin.conf
    register: stat_result

  - name: Clear stale join-command.sh (if needed)
    become: false
    local_action:
      module: file
      path: ../work/join-command.sh
      state: absent
    when: stat_result.stat.exists == false

  - name: Create Kubernetes Cluster
    command:
      cmd: kubeadm init --apiserver-advertise-address="{{node_ip}}" --apiserver-cert-extra-sans="{{node_ip}}" --pod-network-cidr=192.168.0.0/16
      creates: /etc/kubernetes/admin.conf
    register: kubernetes_create
  - debug:
      msg: "{{ kubernetes_create.stdout_lines }}"

  - name: Copy Kubernetes admin.conf
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: ../kube_config_cluster.yml
      flat: yes

  - name: Build Worker join command
    shell:
      cmd: kubeadm token create --ttl 0 --print-join-command > /vagrant/work/join-command.sh
      creates: /vagrant/work/join-command.sh

  - name: Retrieve join-command.sh contents
    slurp:
      src: /vagrant/work/join-command.sh
    register: join_command

  - name: Build Control-Plane join command
    copy:
      content: "{{ join_command['content'] | b64decode }} --control-plane"
      dest: /vagrant/work/join-control-command.sh

  - name: Install Flannel CNI
    local_action:
      module: shell
      cmd: KUBECONFIG=../kube_config_cluster.yml kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    become: false
    register: kubectl_cni
    changed_when: '" created" in kubectl_cni.stdout'
  - debug:
      msg: "{{ kubectl_cni.stdout_lines }}"
  become: true
